#!/usr/bin/env python3
"""Generate GHL Tier 1 workflow audit checklist."""
from pathlib import Path

LOCATION_ID = "3xt4qayAh35BlDLaUv7P"
BASE_URL = f"https://app.gohighlevel.com/v2/location/{LOCATION_ID}/automation"

TIER1_WORKFLOWS = [
    ("11c4943e", "5. Process Message - Which Bot?"),
    ("be1b2b2d", "1. New Lead — Route to Bot"),
    ("d43d02f5", "2. AI OFF/ON Tag Added"),
    ("7ebafcd6", "3. Seller Qualified — Notify Jorge"),
    ("da046656", "4. Buyer Qualified — Notify Jorge"),
    ("64b82875", "6. Hot Lead Follow-Up"),
    ("b886a5e5", "7. Warm Lead Nurture"),
    ("972d8000", "8. Manual Scheduling Fallback"),
]

RISK_QUESTIONS = {
    "d43d02f5": [
        "Does this workflow write the 'Bot Type' custom field? If YES, disable that action — it conflicts with app routing.",
        "Does it only add/remove the Jorge-Active tag?",
    ],
    "11c4943e": [
        "Does this workflow relay EXCLUSIVELY to the app webhook (jorge-realty-ai-xxdf.onrender.com)?",
        "Is there any direct SMS send action? If YES, must be removed.",
        "Does it filter by contactId or locationId?",
    ],
}

DEFAULT_QUESTIONS = [
    "Does this workflow send any SMS directly (bypassing bot)?",
    "Does it write any custom fields that conflict with bot state?",
    "Is the trigger condition narrow enough to avoid double-firing?",
    "Disposition: keep as-is / rewrite / disable",
]


def main():
    lines = [
        "# GHL Tier 1 Workflow Audit Checklist",
        "",
        "Generated by `scripts/generate_workflow_audit_checklist.py`",
        f"Location: `{LOCATION_ID}`",
        "",
        "## Instructions",
        "1. Open each GHL URL below in the GHL UI",
        "2. Answer each risk question by reviewing the workflow steps",
        "3. Record disposition: **keep** / **rewrite** / **disable**",
        "4. Update `docs/JORGE_GHL_WORKFLOW_INVENTORY.md` with results",
        "",
    ]
    for wf_id, name in TIER1_WORKFLOWS:
        url = f"{BASE_URL}/{wf_id}"
        questions = RISK_QUESTIONS.get(wf_id, DEFAULT_QUESTIONS)
        lines.append(f"### {name}")
        lines.append(f"- **ID:** `{wf_id}`")
        lines.append(f"- **URL:** [{url}]({url})")
        lines.append("- **Risk Questions:**")
        for q in questions:
            lines.append(f"  - [ ] {q}")
        lines.append("")

    out = Path("docs/GHL_WORKFLOW_AUDIT_CHECKLIST.md")
    out.write_text("\n".join(lines))
    print(f"Written: {out}")


if __name__ == "__main__":
    main()
